name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger this workflow on tags starting with 'v'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0 # Update this to match your project's .NET version

    - name: Restore Dependencies
      run: dotnet restore ./app/Guidzgo.sln

    - name: Build Project
      run: dotnet build ./app/Guidzgo.sln --configuration Release

    - name: Publish Project
      run: dotnet publish ./app/Guidzgo.sln -c Release -o ./release

    - name: Copy Additional Assets
      run: |
        mkdir release
        copy script\keydrop_giveaway_script.js release\
      shell: cmd

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Compiled Application
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/*.exe
        asset_name: Guidzgo.exe
        asset_content_type: application/vnd.microsoft.portable-executable

    - name: Upload JavaScript Script
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/keydrop_giveaway_script.js
        asset_name: keydrop_giveaway_script.js
        asset_content_type: text/javascript