name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore app/Guidzgo.sln

    - name: Build Solution
      run: msbuild app/Guidzgo.sln /p:Configuration=Release

    - name: Debug Build Output
      run: |
        echo "Checking Release folder..."
        dir app\Guidzgo\bin\Release
        echo "Checking Debug folder..."
        dir app\Guidzgo\bin\Debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          app/Guidzgo/bin/Release/**/*
          app/Guidzgo/bin/Debug/**/*

    - name: Download External Script
      run: |
        curl -o keydrop_giveaway_script.js https://raw.githubusercontent.com/mrFavoslav/KeyDrop-BOT/main/script/keydrop_giveaway_script.js

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/Guidzgo/bin/Release/**/*
          app/Guidzgo/bin/Debug/**/*
          keydrop_giveaway_script.js
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}