name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Restore NuGet packages
      run: nuget restore app/Guidzgo.sln

    - name: Build Release Solution
      run: msbuild app/Guidzgo.sln /p:Configuration=Release
      working-directory: ${{ github.workspace }}

    - name: Build Debug Solution
      run: msbuild app/Guidzgo.sln /p:Configuration=Debug
      working-directory: ${{ github.workspace }}

    - name: Log Directory Structure
      run: tree app /F

    - name: Debug Build Output
      run: |
        if (Test-Path app\Guidzgo\bin\Release) {
          Write-Output "Checking Release folder..."
          Get-ChildItem app\Guidzgo\bin\Release
        } else {
          Write-Output "Release folder not found."
        }

        if (Test-Path app\Guidzgo\bin\Debug) {
          Write-Output "Checking Debug folder..."
          Get-ChildItem app\Guidzgo\bin\Debug
        } else {
          Write-Output "Debug folder not found."
        }

    - name: Upload Artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: |
          app/Guidzgo/bin/Release/**/* 
          app/Guidzgo/bin/Debug/**/*

    - name: Download External Script
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o keydrop_giveaway_script.js \
        https://raw.githubusercontent.com/mrFavoslav/KeyDrop-BOT/refs/heads/main/script/keydrop_giveaway_script.js

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/Guidzgo/bin/Release/Guidzgo.exe
          keydrop_giveaway_script.js
          Source code (zip)
          Source code (tar.gz)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}